
name: aseprite-auto-built

on:
  repository_dispatch:
    types: [build]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build, leave empty for latest"
        required: false
  
jobs:
  build:
    runs-on: windows-2025
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Windows Build
        id: build
        shell: cmd
        run: call build.cmd
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          path: github
          if-no-files-found: error
      
      - name: Zip Aseprite
        run: |
          cd build/bin
          7z a ../../Aseprite-Windows-x64-${{ steps.build.outputs.ASEPRITE_VERSION }}.zip *

      - name: GitHub Released
        uses: softprops/action-gh-release@v2
        with:
          name: Aseprite-Windows-x64-${{ steps.build.outputs.ASEPRITE_VERSION }}
          tag_name: ${{ steps.build.outputs.ASEPRITE_VERSION }}
          files: |
            Aseprite-Windows-x64-${{ steps.build.outputs.ASEPRITE_VERSION }}.zip
      
      - name: save version build
        run: |
          echo asprite-${{ steps.build.outputs.ASEPRITE_VERSION }} >> /build/version.txt
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT }}
          message: "fetch aseprite version"
          directory: /build/version.txt